exec:
  filename: generated/exec.go
model:
  filename: models/generated.go

autobind:
  - sec.com/init/models

models:
  ReviewInput:
    model: models.Review
  Starship:
    fields:
      length:
        resolver: true
