"""khoi_tao_v1

Revision ID: 554c1df03967
Revises: 
Create Date: 2020-04-14 18:14:09.232042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554c1df03967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbounds', sa.Column('new_field_migrate', sa.Integer(), nullable=True))
    op.drop_column('inbounds', 'some_thing_____ok')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbounds', sa.Column('some_thing_____ok', sa.DATE(), nullable=False))
    op.drop_column('inbounds', 'new_field_migrate')
    # ### end Alembic commands ###
