"""int3

Revision ID: 03a6b80a17a5
Revises: 76ef5d65eef9
Create Date: 2020-04-15 22:57:13.841302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a6b80a17a5'
down_revision = '76ef5d65eef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('stt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'stt')
    # ### end Alembic commands ###
