"""Init2

Revision ID: 76ef5d65eef9
Revises: a05fee731ca7
Create Date: 2020-04-15 22:55:36.336279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ef5d65eef9'
down_revision = 'a05fee731ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('stt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'stt')
    # ### end Alembic commands ###
