"""Init4

Revision ID: 84d60ac26db8
Revises: 03a6b80a17a5
Create Date: 2020-04-15 22:59:24.597738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d60ac26db8'
down_revision = '03a6b80a17a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('stt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'stt')
    # ### end Alembic commands ###
