"""remove_product_ref_on_inbound_item

Revision ID: c132634082b0
Revises: 84d60ac26db8
Create Date: 2020-04-16 09:21:28.233138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c132634082b0'
down_revision = '84d60ac26db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inbound_item_ibfk_2', 'inbound_item', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('inbound_item_ibfk_2', 'inbound_item', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
