[default]
SECRET_KEY = 'some_key_abc'
CELERY_BROKER_URL = 'pyamqnqp://:rabbitmq3:rabbitmq3@rabbitmq.tn20.wedesign.vn:9011' 
CELERY_RESULT_BACKEND = ''

# Flask-Mail
MAIL_SERVER = 'smtp.googlemail.com'
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USERNAME = 'bannv2016@gmail.com'
MAIL_PASSWORD = 'xxx'
REDIS_HOST = '27.72.88.106'
REDIS_PORT = 3079

CELERY_ENABLE_UTC = True
CELERY_TIMEZONE='Asia/Ho_Chi_Minh'
